name: NPM Publish Libraries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: |
          echo Installing Dependencies
          sudo npm install -g npm-cli-login
          sudo npm install -g @angular/cli
          npm install
      - name: Build & NPM Login & Publish
        run: |
          ng build impressum
          echo login to npm registry
          NPM_USER=dance-planner NPM_PASS=${{ secrets.authToken }} NPM_EMAIL=richie.dual@dhbw-richie.de NPM_REGISTRY=https://npm.pkg.github.com NPM_SCOPE=@dance-planner-org npm-cli-login --verbose
          cd dist/impressum
          ls
          npm pack
          npm publish --verbose
