name: NPM Publish Libraries

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Installing Dependencies
        run: |
          echo Installing Dependencies
          sudo npm install -g npm-cli-login
          npm install
      - name: Run build
        run: |
          echo run lib:build
          npm run lib:build
      - name: NPM Login & Publish
        run: |
          echo login to npm registry
          NPM_USER=dance-planner NPM_PASS=${{ secrets.authToken }} NPM_EMAIL=richie.dual@dhbw-richie.de NPM_REGISTRY=https://npm.pkg.github.com NPM_SCOPE=@dance-planner npm-cli-login --verbose
          cd ../impressum
          ls
          npm pack
          npm publish --verbose
          cd ../dps
          npm pack
          npm publish --verbose
          cd ../images-grid
          npm pack
          npm publish --verbose
          cd ..
